# Site settings
title: OpenBudgets
description: > # this means to ignore newlines until "baseurl:"
  Upload, Visualize, Analyse public budget and spending data. Start exploring and learn stories behind budgets.
baseurl: "/openbudgets" # the subpath of your site, e.g. /blog/
url: "http://okfnlabs.org" # the base hostname & protocol for your site

github_username:  okfn
github_repo: openbudgets
twitter_username: openbudgetseu
facebook_username:  OKFNetwork

contact: anna.alberts@okfn.de

#googleanalytics: UA-XXXXX-X

# Build settings
markdown: kramdown

permalink: pretty

paginate: 10
paginate_path: "/blog/page:num/"
