# Site settings
title: OpenBudgets
description: > # this means to ignore newlines until "baseurl:"
  Upload, Visualize, Analyse public budget and spending data. Start exploring and learn stories behind budgets.
baseurl: "/openbudgets" # the subpath of your site, e.g. /blog/
url: "http://okfnlabs.org" # the base hostname & protocol for your site

github_username:  okfn

twitter_username: okfn
facebook_username:  OKFNetwork
youtube_username:  openknowledgefdn

contact: anna.alberts@okfn.de

#googleanalytics: UA-XXXXX-X

# Build settings
markdown: kramdown

permalink: pretty